version: 1
jobs:
  test-2.7:
    docker:
      - image: circleci/python:2.7.16-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            python run_tests.py
          when: always
  version: 1
  build:
    jobs:
      - test-2.7
